#!/usr/bin/env bash

ARGS=1

#BASEDIR="/cluster/runs"

source comet_script_settings

if [ $# -ne "$ARGS" ]
then
  echo
  echo "Syntax: checkdone <set identifier>"
  echo
  exit 1
fi

# syntax: checkdone <set>
# called from within the directory that comet is running e.g. $BASEDIR/1/1/

read -d ' ' STEPS variables < $BASEDIR/$1/setparam.txt

#export PATH=$PATH:$HOME/bin
#export LD_LIBRARY_PATH=/home/matt/lib
#export MAGICK_CONFIGURE_PATH=/home/matt/IMconfig/

#source ~/setheadnode

RUNSCOMPLETED=0

for ((a=1; a <= STEPS ; a++))
do

if [ $BASEDIR/${1}/1/x_proj.mov -nt $BASEDIR/${a}/cometparams.ini ]; then
   ((RUNSCOMPLETED = RUNSCOMPLETED + 1))
fi

done

echo "Set ${1} has $RUNSCOMPLETED of $STEPS runs completed"

if [ $RUNSCOMPLETED -eq $STEPS ]; then

echo "Set ${1} Finished"

makematrix ${1}

# makesymsummary ${1}

#echo Set $1 Emailing Image
#IMAGETYPE=jpg
#read variable factor0 factor1 factor2 factor3 factor4 factor5 factor6 factor7 < <(cat $BASEDIR/${1}/setparam.txt)
#ssh $HEADNODE "(echo -e Varying $variable from $factor0 to $factor7 '\n\n' ) | \
# $HOME/bin/mutt -s \"${HEADNODE} Set ${1} Finished\" -a $BASEDIR/${1}/${1}_imagearray.${IMAGETYPE}  \"markdayel@gmail.com\" "

#for ((a=1; a <= STEPS ; a++))
#do

#done

#ssh $HEADNODE "cd $BASEDIR/${1}/1/; $HOME/bin/makeradialmov 1 300 ;\
#               cd $BASEDIR/${1}/2/; $HOME/bin/makeradialmov 1 300 ;\
#               cd $BASEDIR/${1}/3/; $HOME/bin/makeradialmov 1 300 ;\
#               cd $BASEDIR/${1}/4/; $HOME/bin/makeradialmov 1 300 ;\
#               cd $BASEDIR/${1}/5/; $HOME/bin/makeradialmov 1 300 ;\
#               cd $BASEDIR/${1}/6/; $HOME/bin/makeradialmov 1 300 ;\
#               cd $BASEDIR/${1}/7/; $HOME/bin/makeradialmov 1 300 ;\
#               cd $BASEDIR/${1}/8/; $HOME/bin/makeradialmov 1 300 "

#read variable factor0 factor1 factor2 factor3 factor4 factor5 factor6 factor7 < <(cat setparam.txt)
#echo Set ${1} Finished.  Varying  $variable from $factor0 to $factor7 | mutt -s "ec3.ucsf.edu Set ${1} Finished" -a imagearray${1}.jpg "markdayel@gmail.com"

## all done, so it's safe to change the name of the directory
#cd $HOME
#mv $BASEDIR/${1} $BASEDIR/$IDENTIFIER

fi
