#!/usr/bin/env bash

# data processing script for use with comet 
# (c) Mark J Dayel 2009
# 
# removes specified measurements from nodetracksedit.txt and nodedistances.txt files 
# find reference numbers for measurements to remove by using
# comet view <frame>:<frame>
# then specify nodes to remove below
# original nodetracksedit.txt and nodedistances.txt files are backed up

NODESTOREMOVE="10 11 2"

#remove duplicates
NODESTOREMOVE=`echo $NODESTOREMOVE | tr " " "\n" | sort -un | xargs`

#backup the old nodetracks file
IDENTIFIER=`date +"%m-%d-%y_%H%M"`
echo Backup up old files
cp -v nodetracks.txt nodetracks_$IDENTIFIER.txt
cp -v nodedistances.txt nodedistances$IDENTIFIER.txt

TOTNODES=`head -n 1 nodetracks.txt`
HALFNODES=`expr $TOTNODES / 2`

NODENUMBERS="` awk 'NR==2{print;exit}' nodetracks.txt `"

cp nodetracks.txt nodetracksedit.txt

NODESLIST="$NODENUMBERS"

for NODE in $NODESTOREMOVE
do

FIRST=`echo $NODENUMBERS | cut -d' ' -f$NODE`

LASTPOS=`expr $NODE + $HALFNODES`

LAST=`echo $NODENUMBERS | cut -d' ' -f$LASTPOS`
#echo cut -d' ' -f$NODE

echo Removing tracks for nodes $FIRST and $LAST "(measure reference no $NODE)" | tee -a nodesremoved.log

grep "^$FIRST|^$LAST" -v nodetracksedit.txt > nodetracksedittmp.txt
grep "^[0-9]* $FIRST" -v nodedistances.txt > nodedistancestmp.txt

mv nodetracksedittmp.txt nodetracksedit.txt
mv nodedistancestmp.txt nodedistances.txt

((TOTNODES = TOTNODES - 2))

# remove the node from the list
NODESLIST=${NODESLIST//$FIRST/}
NODESLIST=${NODESLIST//$LAST/}

done

LINES=`wc -l nodetracksedit.txt | xargs | cut -d' ' -f1`

((LINES = LINES - 2))

echo $TOTNODES > nodetracks.txt
echo $NODESLIST >> nodetracks.txt
tail -n $LINES nodetracksedit.txt >> nodetracks.txt




 
