#!/usr/bin/env bash

tmpdir=`mktemp -d -t process_comet_distances` 

if [ "$tmpdir" == "" ] ; then
        echo "unable to create temp dir"
        exit
fi

echo Using temp dir: $tmpdir

sort -k 2n -k 1n nodedistances.txt | uniq > $tmpdir/nodedistances1.txt

cat $tmpdir/nodedistances1.txt | cut -d' ' -f1-3 > $tmpdir/nodedistances2.txt

cat $tmpdir/nodedistances2.txt | cut -d' ' -f1 | sort -k 1n | uniq  >  $tmpdir/framenos.txt
cat $tmpdir/nodedistances2.txt | cut -d' ' -f2 | sort -k 1n | uniq  >  $tmpdir/nodenos.txt
cat $tmpdir/nodedistances2.txt | cut -d' ' -f2,3  >  $tmpdir/frameanddistances.txt

cat $tmpdir/framenos.txt | tr '\n' ' ' > $tmpdir/distoutput.txt
echo >> $tmpdir/distoutput.txt

cat $tmpdir/nodenos.txt | while read NODENUM
do

grep ^$NODENUM $tmpdir/frameanddistances.txt | cut -d' ' -f2 | tr '\n' ' ' >> $tmpdir/distoutput.txt
echo >> $tmpdir/distoutput.txt

done

awk -F " " '{
for (f = 1; f <= NF; f++)
a[NR, f] = $f
}
NF > nf { nf = NF }
END {
for (f = 1; f <= nf; f++)
for (r = 1; r <= NR; r++)
printf a[r, f] (r==NR ? RS : FS)
}' $tmpdir/distoutput.txt | sed -e '/^ /d' > $tmpdir/distoutput2.txt

# the above sed command removes lines beginning with space 
# (for some reason the transpose includes a full copy of the 
# input at the end with spaces beginning each line...)

echo -n "Frame," > distoutput.csv
cat $tmpdir/nodenos.txt | sed "s/^/dist_/" | tr '\n' ',' >> distoutput.csv
echo >> distoutput.csv
cat $tmpdir/distoutput2.txt | sed -e 's/1e-19//g' | tr ' ' ',' >> distoutput.csv
