#!/usr/bin/env bash

#BASEDIR="/cluster/runs"
#HOSTS="b1 b2 b3 b4 b5"

# note: expects 'sensors' to be installed to be able to return the node cpu temp

echo

#date
source comet_script_settings

bold=`tput smso` 
offbold=`tput sgr0`

FREENODES=0
NODESDOWN=0

tempdir=`mktemp -d /tmp/jobstat.XXXXXX` || exit 1

screen -list > $tempdir/screenlist.txt

touch  $tempdir/unsorted.txt
touch  $tempdir/errors.txt
touch  $tempdir/errors2.txt

echo -n Scanning hosts

for MACHINE in $HOSTS
do
	#echo -n " Host $MACHINE: " >&2
	echo -n .

	REMOTEUPTIME=`ssh -oConnectTimeout=1 -x $MACHINE "uptime ; sensors | grep temp3 | tr -s ' ' ' ' | cut -d' ' -f2 " 2>>$tempdir/errors2.txt`
	if [ "$?" -eq 255 ] ; then
		echo -n "HOST $MACHINE IS DOWN (" >> $tempdir/errors.txt
		echo -n ")" | cat $tempdir/errors2.txt - | tr -d '\n' | tr -d '\r'  >> $tempdir/errors.txt
		echo >> $tempdir/errors.txt
		rm $tempdir/errors2.txt
		touch  $tempdir/errors2.txt
		((NODESDOWN=NODESDOWN+1))
		continue
	fi
	#echo $REMOTEUPTIME
	TEMP=`echo $REMOTEUPTIME | cut -d'+' -f2`
	LOAD1MIN=$(echo $REMOTEUPTIME | awk -F "load avera.*:" '{ print $2 }' | cut -d, -f1)
	LOAD5MIN=$(echo $REMOTEUPTIME | awk -F "load avera.*:" '{ print $2 }' | cut -d, -f2)
	SCREEN=`grep $MACHINE $tempdir/screenlist.txt | cut -d. -f2`

	MACHINE=`printf "% 10s" $MACHINE`

	IDENTIFIER=${SCREEN:0:13}

	if [ ! "$IDENTIFIER" == "" ]; then

		IDEN2=${SCREEN:14:100}

		HOST=${IDEN2#*_}

		RUN=${IDEN2%_*}

		INFOFILE="$BASEDIR/${IDENTIFIER}/${RUN}/comet_run_info.txt"
		SYMBREAKFILE="$BASEDIR/${IDENTIFIER}/${RUN}/sym_break_axis.txt"
		#echo $INFOFILE

		# find frame number from end of info file

		FRAME=""

		if [ -f "$INFOFILE" ] ; then
			FRAME=`tail -1 $INFOFILE | cut -c45-80 `
		fi

		# add a '*' if not broken sym

		if [ ! -f "$SYMBREAKFILE" ] ; then
			FRAME="$FRAME *"
		fi
		
		# count free nodes
		grep -q $MACHINE $tempdir/screenlist.txt
		if [ "$?" -eq "1" ] ; then 
			(( FREENODES = FREENODES + 1))
		fi
		
else

	IDENTIFIER="(no job running)"
	RUN=
	FRAME=
fi

	RUN=`printf %2s $RUN`
	echo "$MACHINE $LOAD1MIN $LOAD5MIN $IDENTIFIER $RUN $FRAME $TEMP" >> $tempdir/unsorted.txt
done
echo done

cat $tempdir/errors.txt

echo $bold
echo "   Machine  1mld  5mld       ID       R       T     Frame   Temp $offbold"

cat $tempdir/unsorted.txt | sort -k4,5


rm $tempdir/screenlist.txt $tempdir/unsorted.txt $tempdir/errors.txt $tempdir/errors2.txt
rmdir $tempdir

#done
echo

echo $FREENODES nodes free

if [ -f $BASEDIR/joblist ]; then
	WAITINGJOBS=`wc -l $BASEDIR/joblist | cut -d ' ' -f1 `
	echo $WAITINGJOBS jobs waiting
else
	echo "$boldNo joblist file found ($BASEDIR/joblist)$offbold"
fi

if [ "$NODESDOWN" -ne "0" ]; then
	echo "$bold$NODESDOWN nodes down!$offbold"
fi

echo
