#!/usr/bin/env bash

source comet_script_settings

echo Killing comet processes:
for MACHINE in $HOSTS
do
echo Host: $MACHINE
ssh -oConnectTimeout=1 -x $MACHINE killall comet
done

echo
sleep 1
echo Checking for processes still running:
for MACHINE in $HOSTS
do
echo Host: $MACHINE
ssh -oConnectTimeout=1 -x $MACHINE ps -A | grep comet | grep -v grep
done

echo

echo Waiting 5 seconds...
sleep 5

jobstat
