#!/usr/bin/env bash

# syntax go <set>

source comet_script_settings


#BASEDIR="/cluster/runs"


read -d ' ' STEPS variables < $BASEDIR/$1/setparam.txt

# order steps to give greatest info first

case "$STEPS" in
'1')
STEPSTR="1"
;;
'2')
STEPSTR="1 2"
;;
'3')
STEPSTR="1 3 2"
;;
'4')
STEPSTR="1 4 2 3"
;;
'5')
STEPSTR="1 5 3 2 4"
;;
'6')
STEPSTR="1 6 3 5 2 4"
;;
'7')
STEPSTR="1 7 4 2 6 3 5"
;;
'8')
STEPSTR="1 8 4 6 2 7 3 5"
;;
'9')
STEPSTR="1 9 5 3 7 2 6 4 8"
;;
'10')
STEPSTR="1 10 5 3 7 2 6 4 8 9"
;;
esac

for a in $STEPSTR
do
addjob ${1}_${a} /cluster/comet/scripts/startrun $1 $a
done




#read -d ' ' STEPS variables < $HOME/runs/$1/setparam.txt

#for ((a=1; a <= STEPS ; a++))
#do
#addjob ${1}_${a} $HOME/bin/startrun $1 $a
#done
