#!/usr/bin/env bash

#BASEDIR="/cluster/runs"

source comet_script_settings
ARGS=4

if [ $# -ne "$ARGS" ]
then
  echo
  echo "Syntax: varyset <parameter> <startval> <endval> <number of steps>"
  echo
  exit 1
fi

STEPS=$4

read RUNID <~/runid

((RUNID = RUNID + 1))

echo $RUNID >~/runid

IDNUM=`printf "%04d" $RUNID `

#IDENTIFIER=`date +"%m-%d-%y_%H%M_$IDNUM"`
IDENTIFIER=`date +"%m-%d-%y_$IDNUM"`

((STEPSLESSONE = STEPS - 1))

mkdir -p $BASEDIR/${IDENTIFIER}
cp $BASEDIR/cometparams.ini $BASEDIR/${IDENTIFIER}
touch $BASEDIR/${IDENTIFIER}/"$1 $2 $3"

echo -n "$STEPS $1" > $BASEDIR/${IDENTIFIER}/setparam.txt

for ((a=1; a <= STEPS ; a++))
do

((currlessone = a - 1))

mkdir -p $BASEDIR/${IDENTIFIER}/$a

factor=`echo "scale=3; $2 + ( ($3 - $2) * ${currlessone} ) / ${STEPSLESSONE}" | bc -l`

sed '/'^$1'.*$/s//'$1' '$factor'/' $BASEDIR//cometparams.ini > \
    $BASEDIR//${IDENTIFIER}/${a}/cometparams.ini

touch $BASEDIR/${IDENTIFIER}/${a}/"$1 $factor"

echo -n " $factor" >> $BASEDIR/${IDENTIFIER}/setparam.txt

done

echo " ">> $BASEDIR/${IDENTIFIER}/setparam.txt

echo "Parameter:$1  Min:$2  Max:$3  Steps:$STEPS"
cat $BASEDIR/${IDENTIFIER}/setparam.txt
echo "Set identifier: $IDENTIFIER"

echo

# add jobs to the list:
sgego ${IDENTIFIER}
